name: Simple Deploy Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Test AWS connection
      run: |
        echo "Testing AWS connection..."
        aws sts get-caller-identity
        
    - name: Test ECR access
      run: |
        echo "Testing ECR access..."
        aws ecr describe-repositories --repository-names document-portal
        
    - name: Success
      run: |
        echo "✅ AWS credentials and ECR access working!"
