name: Working Full Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: document-portal
  ECS_CLUSTER: dev-document-portal-cluster
  ECS_SERVICE: dev-document-portal-service
  ECS_TASK_DEFINITION: dev-document-portal-task

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Test AWS connection
      run: |
        echo "Testing AWS connection..."
        aws sts get-caller-identity
        echo "AWS connection successful!"

    - name: Test ECR access
      run: |
        echo "Testing ECR access..."
        aws ecr describe-repositories --repository-names document-portal
        echo "ECR access successful!"

    - name: Test ECS access
      run: |
        echo "Testing ECS access..."
        aws ecs describe-clusters --clusters dev-document-portal-cluster
        aws ecs describe-services --cluster dev-document-portal-cluster --services dev-document-portal-service
        echo "ECS access successful!"

    - name: Test Docker
      run: |
        echo "Testing Docker..."
        docker --version
        echo "Docker available!"

    - name: Success
      run: |
        echo "🎉 All components are working!"
        echo "Ready for full deployment!"
